export const actionType = 'actionType'
export const filtertype = 'filtertype'
export const ADD_HOTEL = 'ADD_HOTEL'
export const FILTER_LOCATION = 'FILTER_LOCATION'
export const FILTER_RATE = 'FILTER_RATE'
